### PR TITLE
core: split tail_message

### PR DESCRIPTION
**Pull request by mathstuf**
Split tail_message into:

  - _create_poller
  - _poll
  - _poll_socket
  - _close_subs

This allows the polling to be hooked into another event loop.

---
Not sure if this is the best way to do this.

### CODE REVIEW

**Comment by ralphbean** [comment]
:+1: to the concept but I want to review the code more closely when I'm back from PTO.  If anyone else wants to give it a review in the meantime, the more eyes the better.  Thanks @mathstuf!

**Comment by ralphbean** [comment]
@mathstuf this is great.

Can you rebase against develop to get it in a state for merging?  Sorry I didn't get back to this sooner.

**Comment by mathstuf** [comment]
Rebased.

**Comment by ralphbean** [comment]
Thanks again :)

**Pull request merged**
