### PR TITLE
Fix setting headers in message body

### PR DESCRIPTION
**Pull request by hluk**
Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by gnaponie** [comment]
Seems like tox is failing on the CI, could you check it?

**Comment by gnaponie** [comment]
Besides the CI failing the change looks good.
+1 once that's fixed.

**Comment by hluk** [comment]
> Seems like tox is failing on the CI, could you check it?

Those failing tests seem to be unrelated to the fix.

I haven't been able to run the tests locally without a failure even on develop branch.

**Comment by gnaponie** [comment]
Feel free to merge this if you want to. Maybe let's consider fixing the CI with a separate MR.

**Review by mvalik — APPROVED** [review]

**Review by gnaponie — APPROVED** [review]

**Comment by hluk** [comment]
I fixed the tests. Anyone can review and merge this? Maybe @ralphbean ?

**Comment by ralphbean** [comment]
This should be resolved in #526

**Pull request closed without merging**
