### PR TITLE
ZMQMessage isn't iterable, use __dict__

### PR DESCRIPTION
**Pull request by relrod**
This was flooding logs with traces after we did updates on 2017-08-09. This is the hotfix I came up with, but if it's fixed another way that's fine with me too. Just wanted to get this out there.

### CODE REVIEW

**Comment by relrod** [comment]
It looks like sometimes this method gets called with a dict and other times with a ZMQMessage? Or the tests are wrong. It was definitely a ZMQMessage in the traces we were seeing, but the tests seem to pass it a dict (which is why they failed).

**Comment by jeremycline** [comment]
Oof. I think the tests are wrong, but because the API isn't defined at all I have no idea. I'll do some research on this.

**Comment by jeremycline** [comment]
Okay, none of the moksha APIs are defined or documented and it's a tangled mess of functions accepting "messages" so it's not trivial to say what might break if we suddenly switch from the ZMQMessage class to a plain dict.

My inclination is to either revert the commit that added this and spend some time auditing everything and writing careful tests, or add a check to see if it's a dict before placing headers in the body. @ralphbean, since this is a feature you needed, do you have an opinion one way or the other?

**Comment by ralphbean** [comment]
> add a check to see if it's a dict before placing headers in the body.

This seems like the most practical approach for now, no?

**Review by ralphbean — APPROVED** [review]

**Pull request merged**
