### PR TITLE
Use irc logger instead of moksha.hub.

### PR DESCRIPTION
**Pull request by ralphbean**
This will make debugging much easier.  Currently, if connections fail you see
"[moksha.hub] Could not connect".  After this change you should see
"[fedmsg.consumers.ircbot] Could not connect." which gives much better
information.

### CODE REVIEW

**Comment by jeremycline** [comment]
The change itself looks fine to me (all the logging needs similar treatment), but unfortunately it looks like there's no test coverage for that module so the diff coverage is 0%. Could you write some basic tests for that module? If you don't have time that's fine, but it'll be a while before I can get to it.

**Comment by ralphbean** [comment]
> Could you write some basic tests for that module?

Sorry, I'm slammed.  :(

**Comment by ralphbean** [comment]
> Could you write some basic tests for that module?

Started in #432.

**Comment by jeremycline** [comment]
Could you rebase onto develop to pick up the newest tests?

**Comment by ralphbean** [comment]
> Could you rebase onto develop to pick up the newest tests?

Yes.  Done.  Thanks.  :)

**Review by jeremycline — APPROVED** [review]
As much as I'd like test coverage for this module, I would prefer to make a release and this is a fairly safe change.

**Pull request merged**
