### PR TITLE
Allow fedmsg-tail to be daemonizable

### PR DESCRIPTION
**Pull request by pabelanger**
Fedmsg-tail is a great tool for testing, however it currently required
2 terminals (or screen) to be used properly.  Fedmsg already support
other commands to be run as daemons, so lets add that support to
fedmsg-tail.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Well, fedmsg-tail is meant to be used to show the traffic of a bus on the screen, so I'm not quite sure it makes sense to have it be a daemon.
Where would the output be printed in daemon mode?

**Comment by pabelanger** [comment]
/var/log/fedmsg/fedmsg-tail.log

This is helpful so I don't have to write my own logic for a screen session. In my example below, we are just using fedmsg-tail as part of an integration test, to validate fedmsg.publish() works correctly.

https://review.openstack.org/#/c/426861/17/tools/nodepool-integration-setup.sh

**Comment by pypingou** [comment]
Hm looks like this impact some of the tests

**Comment by jeremycline** [comment]
Hi @pabelanger, what I tend to do is run fedmsg-tail as a systemd-controlled service. Would that work for you?

More generally I'm wondering if we want to drop the daemonization support in fedmsg and just have users use systemd.

**Comment by ralphbean** [comment]
> More generally I'm wondering if we want to drop the daemonization support in fedmsg and just have users use systemd.

:+1: to this.  :)

**Comment by jeremycline** [comment]
Since we've decided to deprecate the daemon feature entirely, I'm going to go ahead and close this PR. Thanks, though!

**Pull request closed without merging**
