### PR TITLE
Add Python 3 support to fedmsg

### PR DESCRIPTION
**Pull request by jeremycline**
This adds Python 3 support to fedmsg. Tests are run against 3.4+.

### CODE REVIEW

**Comment by pypingou** [comment]
Nice and clean, looks fine to me! :)

**Comment by jeremycline** [comment]
I believe this also depends on #448 since with nose the tests hang on Python 3. I was working off that branch and rebased before I made this PR. I don't know _why_ nose causes the tests to hang on Python 3, though :(

**Comment by jeremycline** [comment]
Okay, I had to tweak a few more things to get CI passing, so it probably wouldn't hurt for this to get a second look.

**Comment by pypingou** [comment]
Still looking good to me 👍

**Pull request merged**
