### PR TITLE
Handle multiline json

### PR DESCRIPTION
**Pull request by sijis**
This is an attempt to fix issue #372.

### CODE REVIEW

**Comment by sijis** [comment]
This is what i used as a test case:
`curl -s https://httpbin.org/get | fedmsg-logger --json-input`

**Comment by ralphbean** [comment]
@glensc can you confirm that this fixes #372?

**Comment by pypingou** [comment]
@glensc did you see @ralphbean 's question?

**Comment by glensc** [comment]
i'm sure you can merge without my answer. @sijis said it was tested:
https://github.com/fedora-infra/fedmsg/pull/392#issuecomment-263943704

**Comment by pypingou** [comment]
Alright, let's merge then :)

Thanks for the patch @sijis

**Pull request merged**
